//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasaMenu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasaMenuEntities : DbContext
    {
        public MasaMenuEntities()
            : base("name=MasaMenuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grup> grup { get; set; }
        public virtual DbSet<hesap> hesap { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<masalar> masalar { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<siparis> siparis { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
    }
}
