//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasaMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public int id { get; set; }
        public Nullable<int> masa_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public string zaman { get; set; }
    
        public virtual masalar masalar { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
